"""criar todas as tabelas

Revision ID: 1c2826492546
Revises:
Create Date: 2026-05-29 11:24:48.158290

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1c2826492546'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bombeiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('patente', sa.Enum('soldado', 'cabo', 'sargento', 'tenente', 'capitao', name='patentebombeiro'), nullable=False),
    sa.Column('especialidade', sa.String(length=50), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ativo', 'inativo', 'de_folga', name='statusbombeiro'), nullable=False),
    sa.Column('data_admissao', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bombeiro_id'), 'bombeiro', ['id'], unique=False)
    op.create_index(op.f('ix_bombeiro_matricula'), 'bombeiro', ['matricula'], unique=True)
    op.create_table('denuncia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitante', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('endereco_informado', sa.String(length=150), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'em_analise', 'arquivada', 'convertida', name='statusdenuncia'), nullable=False),
    sa.Column('data_denuncia', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_denuncia_id'), 'denuncia', ['id'], unique=False)
    op.create_table('equipamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('combate', 'resgate', 'medico', 'comunicacao', name='tipoequipamento'), nullable=False),
    sa.Column('numero_serie', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('disponivel', 'em_uso', 'em_manutencao', name='statusequipamento'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipamento_id'), 'equipamento', ['id'], unique=False)
    op.create_index(op.f('ix_equipamento_numero_serie'), 'equipamento', ['numero_serie'], unique=True)
    op.create_table('equipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ativa', 'inativa', name='statusequipe'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipe_id'), 'equipe', ['id'], unique=False)
    op.create_table('treinamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.Enum('teorico', 'pratico', name='tipotreinamento'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('instrutor', sa.String(length=100), nullable=False),
    sa.Column('carga_horaria', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('agendado', 'em_andamento', 'concluido', 'cancelado', name='statustreinamento'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treinamento_id'), 'treinamento', ['id'], unique=False)
    op.create_table('viatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.Enum('auto_bomba', 'auto_escada', 'ambulancia', 'veiculo_leve', name='tipoviatura'), nullable=False),
    sa.Column('ano_fabricacao', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('disponivel', 'em_atendimento', 'em_manutencao', name='statusviatura'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viatura_id'), 'viatura', ['id'], unique=False)
    op.create_index(op.f('ix_viatura_placa'), 'viatura', ['placa'], unique=True)
    op.create_table('bombeiro_equipe',
    sa.Column('bombeiro_id', sa.Integer(), nullable=False),
    sa.Column('equipe_id', sa.Integer(), nullable=False),
    sa.Column('data_alocacao', sa.Date(), nullable=True),
    sa.Column('funcao', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['bombeiro_id'], ['bombeiro.id'], ),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipe.id'], ),
    sa.PrimaryKeyConstraint('bombeiro_id', 'equipe_id')
    )
    op.create_table('bombeiro_treinamento',
    sa.Column('bombeiro_id', sa.Integer(), nullable=False),
    sa.Column('treinamento_id', sa.Integer(), nullable=False),
    sa.Column('status_participacao', sa.Enum('inscrito', 'concluido', 'reprovado', 'desistiu', name='statusparticipacao'), nullable=False),
    sa.Column('data_conclusao', sa.Date(), nullable=True),
    sa.Column('observacao', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['bombeiro_id'], ['bombeiro.id'], ),
    sa.ForeignKeyConstraint(['treinamento_id'], ['treinamento.id'], ),
    sa.PrimaryKeyConstraint('bombeiro_id', 'treinamento_id')
    )
    op.create_table('manutencao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('preventiva', 'corretiva', name='tipomanutencao'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('custo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'em_andamento', 'concluida', name='statusmanutencao'), nullable=False),
    sa.Column('viatura_id', sa.Integer(), nullable=True),
    sa.Column('equipamento_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamento.id'], ),
    sa.ForeignKeyConstraint(['viatura_id'], ['viatura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manutencao_id'), 'manutencao', ['id'], unique=False)
    op.create_table('solicitacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denuncia_id', sa.Integer(), nullable=False),
    sa.Column('comandante_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('prioridade', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('recebida', 'verificada', 'arquivada', 'convertida', name='statussolicitacao'), nullable=False),
    sa.Column('arquivada', sa.Boolean(), nullable=False),
    sa.Column('data_verificacao', sa.DateTime(), nullable=True),
    sa.Column('data_arquivamento', sa.DateTime(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comandante_id'], ['bombeiro.id'], ),
    sa.ForeignKeyConstraint(['denuncia_id'], ['denuncia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('denuncia_id')
    )
    op.create_index(op.f('ix_solicitacao_id'), 'solicitacao', ['id'], unique=False)
    op.create_table('viatura_equipamento',
    sa.Column('viatura_id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamento.id'], ),
    sa.ForeignKeyConstraint(['viatura_id'], ['viatura.id'], ),
    sa.PrimaryKeyConstraint('viatura_id', 'equipamento_id')
    )
    op.create_table('ocorrencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitacao_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('incendio', 'acidente', 'resgate', 'inundacao', 'outros', name='tipoocorrencia'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('prioridade', sa.Enum('baixa', 'media', 'alta', 'critica', name='prioridadeocorrencia'), nullable=False),
    sa.Column('status', sa.Enum('aberta', 'em_andamento', 'encerrada', name='statusocorrencia'), nullable=False),
    sa.Column('num_vitimas', sa.Integer(), nullable=False),
    sa.Column('data_abertura', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_encerramento', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solicitacao_id')
    )
    op.create_index(op.f('ix_ocorrencia_id'), 'ocorrencia', ['id'], unique=False)
    op.create_table('endereco_ocorrencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ocorrencia_id', sa.Integer(), nullable=False),
    sa.Column('logradouro', sa.String(length=150), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.ForeignKeyConstraint(['ocorrencia_id'], ['ocorrencia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ocorrencia_id')
    )
    op.create_index(op.f('ix_endereco_ocorrencia_id'), 'endereco_ocorrencia', ['id'], unique=False)
    op.create_table('ocorrencia_bombeiro',
    sa.Column('ocorrencia_id', sa.Integer(), nullable=False),
    sa.Column('bombeiro_id', sa.Integer(), nullable=False),
    sa.Column('funcao', sa.String(length=50), nullable=True),
    sa.Column('data_participacao', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bombeiro_id'], ['bombeiro.id'], ),
    sa.ForeignKeyConstraint(['ocorrencia_id'], ['ocorrencia.id'], ),
    sa.PrimaryKeyConstraint('ocorrencia_id', 'bombeiro_id')
    )
    op.create_table('ocorrencia_viatura',
    sa.Column('ocorrencia_id', sa.Integer(), nullable=False),
    sa.Column('viatura_id', sa.Integer(), nullable=False),
    sa.Column('funcao', sa.String(length=50), nullable=True),
    sa.Column('hora_inicio', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('hora_fim', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ocorrencia_id'], ['ocorrencia.id'], ),
    sa.ForeignKeyConstraint(['viatura_id'], ['viatura.id'], ),
    sa.PrimaryKeyConstraint('ocorrencia_id', 'viatura_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ocorrencia_viatura')
    op.drop_table('ocorrencia_bombeiro')
    op.drop_index(op.f('ix_endereco_ocorrencia_id'), table_name='endereco_ocorrencia')
    op.drop_table('endereco_ocorrencia')
    op.drop_index(op.f('ix_ocorrencia_id'), table_name='ocorrencia')
    op.drop_table('ocorrencia')
    op.drop_table('viatura_equipamento')
    op.drop_index(op.f('ix_solicitacao_id'), table_name='solicitacao')
    op.drop_table('solicitacao')
    op.drop_index(op.f('ix_manutencao_id'), table_name='manutencao')
    op.drop_table('manutencao')
    op.drop_table('bombeiro_treinamento')
    op.drop_table('bombeiro_equipe')
    op.drop_index(op.f('ix_viatura_placa'), table_name='viatura')
    op.drop_index(op.f('ix_viatura_id'), table_name='viatura')
    op.drop_table('viatura')
    op.drop_index(op.f('ix_treinamento_id'), table_name='treinamento')
    op.drop_table('treinamento')
    op.drop_index(op.f('ix_equipe_id'), table_name='equipe')
    op.drop_table('equipe')
    op.drop_index(op.f('ix_equipamento_numero_serie'), table_name='equipamento')
    op.drop_index(op.f('ix_equipamento_id'), table_name='equipamento')
    op.drop_table('equipamento')
    op.drop_index(op.f('ix_denuncia_id'), table_name='denuncia')
    op.drop_table('denuncia')
    op.drop_index(op.f('ix_bombeiro_matricula'), table_name='bombeiro')
    op.drop_index(op.f('ix_bombeiro_id'), table_name='bombeiro')
    op.drop_table('bombeiro')
    # ### end Alembic commands ###
