"""add aprovada to StatusDenuncia

Revision ID: 6da14f7621e5
Revises: b28d0683ed30
Create Date: 2026-06-22 11:49:30.039554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6da14f7621e5'
down_revision: Union[str, Sequence[str], None] = 'b28d0683ed30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
