"""add inativa to StatusManutencao

Revision ID: b28d0683ed30
Revises: ce1e3d7ff00b
Create Date: 2026-06-22 10:50:44.656599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b28d0683ed30'
down_revision: Union[str, Sequence[str], None] = 'ce1e3d7ff00b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
